[build]
  base = ""
  publish = "public"
  command = "composer install"

[context.production.environment]
  DB_HOST = "127.0.0.1"
  DB_NAME = "dette"
  DB_USER = "mhd"
  DB_PASSWORD = "passer"
  
  [functions]
  directory = "netlify/functions"